#!/usr/bin/env python3
"""Contract Generator — UserPromptSubmit hook.

Reads stdin JSON {prompt, session_id, ...}. If the prompt invokes
claude-reasoning, writes an execution contract for this session.

Model never writes this file; the environment generates it.
"""
import json
import os
import re
import sys
import time

CONTRACTS_DIR = os.path.expanduser("~/.claude/reasoning-contracts")

# Hard contract: A2 execution rule 1 "Must actually call mcp__unified-fetch__status"
HARD_REQUIRED = [
    {
        "stage": "A2",
        "tool": "mcp__unified-fetch__status",
        "min_count": 1,
        "why": "A2 contract execution rule 1: Must actually call unified-fetch status to detect platform mode",
    }
]

# Soft contract: checked at --runtime as WARN, not blocking
SOFT_REQUIRED = [
    {
        "stage": "stage-3",
        "tool_group": ["mcp__unified-fetch__search", "mcp__unified-fetch__scrape", "mcp__unified-fetch__smart_browse"],
        "min_count": 1,
        "why": "Stage 3 verification requires actual search/browse/scrape unless C1 skip applies",
    },
    {
        "stage": "stage-0/1/2/5",
        "tool": "mcp__sequential-thinking__sequentialthinking",
        "min_count": 0,  # 0 = advisory; actual requirement depends on can_branch
        "why": "DAG branching when sequential-thinking available",
    },
]


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # malformed input: never fail the hook

    prompt = payload.get("prompt", "") or ""
    session_id = payload.get("session_id", "") or "unknown"

    # Only engage when this is a claude-reasoning invocation
    if "claude-reasoning" not in prompt:
        sys.exit(0)

    os.makedirs(CONTRACTS_DIR, exist_ok=True)

    # Extract mode/domain hints from prompt for the contract record
    mode_hint = None
    for m in ("diagnostic", "design", "decision", "optimization", "innovation", "general"):
        if re.search(r"\b" + m + r"\b", prompt):
            mode_hint = m
            break

    contract = {
        "session_id": session_id,
        "created_ts": int(time.time()),
        "mode_hint": mode_hint,
        "hard_required": HARD_REQUIRED,
        "soft_required": SOFT_REQUIRED,
        "note": "Generated by UserPromptSubmit hook. Model must not edit.",
    }

    path = os.path.join(CONTRACTS_DIR, session_id + ".json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(contract, f, ensure_ascii=False, indent=2)

    # Always allow the prompt
    print(json.dumps({"decision": "allow"}))


if __name__ == "__main__":
    main()